name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]   # change to master if that's your branch
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Debug env
        run: |
          echo "HF username: Yash12930"
          echo "Space: model"
          echo "Branch: $GITHUB_REF"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://Yash12930:$HF_TOKEN@huggingface.co/spaces/Yash12930/model
          git push --force space main || git push --force space master
